name: flutter_app_template
description: 'A Flutter app template.'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    get: ^4.6.6
    flutter_native_splash: ^2.4.3
    flutter_dotenv: ^5.2.1
    flutter_launcher_icons: ^0.14.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
    #   - images/a_dot_ham.jpeg

    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
