name: flutter_app_template
description: 'A Flutter app template.'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    get: ^4.6.6
    flutter_native_splash: ^2.4.3
    flutter_dotenv: ^5.2.1
    flutter_launcher_icons: ^0.14.1
    flutter_svg: ^2.0.15
    google_fonts: ^6.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
        - fonts/
        - assets/illustrations/
